In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

iris = load_iris()
x = iris.data
y = iris.target
print('Size of Iris dataset : ', x.shape)
print('Size of Iris dataset : ', y.shape)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

print('Size of Train dataset : ', x_train.shape)
print('Size of Train targets : ', y_train.shape)
print('Size of Test dataset : ', x_test.shape)
print('Size of Test targets : ', y_test.shape)

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train, y_train)
predictions = knn_model.predict(x_test)
print(predictions)

print("Training accuracy Score is : ", accuracy_score(y_train, knn_model.predict(x_train)))
print("Testing accuracy Score is : ", accuracy_score(y_test, knn_model.predict(x_test)))
print("Training Confusion Matrix is : \n", confusion_matrix(y_train, knn_model.predict(x_train)))
print("Testing Confusion Matrix is : \n", confusion_matrix(y_test, knn_model.predict(x_test)))

Size of Iris dataset :  (150, 4)
Size of Iris dataset :  (150,)
Size of Train dataset :  (105, 4)
Size of Train targets :  (105,)
Size of Test dataset :  (45, 4)
Size of Test targets :  (45,)
[0 0 1 0 1 2 0 2 0 1 2 0 2 0 1 2 0 2 2 1 2 2 1 2 2 1 1 2 1 0 2 1 1 2 1 2 0
 0 0 0 2 1 2 1 2]
Training accuracy Score is :  0.9904761904761905
Testing accuracy Score is :  0.9333333333333333
Training Confusion Matrix is : 
 [[37  0  0]
 [ 0 35  0]
 [ 0  1 32]]
Testing Confusion Matrix is : 
 [[13  0  0]
 [ 0 13  2]
 [ 0  1 16]]
